### ISSUE TITLE
Downloaded weight file is corrupted

### ISSUE THREAD

**Issue by kirandhakal25** [adarsh1001/Hand_Segmentation_RefineNet#2]
Hi Adarsh,

I downloaded the file "hands.pth.tar" and tried to extract using the command "tar -xvf hands.pth.tar". I got the following error:
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

I suspect the file is corrupted. Could you please upload it again?
Thanks.

**Comment by adarsh1001** [comment]
Hi @kirandhakal25, this isn't a tarball at all. It's a checkpoint file generated by PyTorch's `save()`. The `.tar` in the extension is a bit misleading but that is the convention the community used to follow a couple of years ago. You can directly load this `*.pth.tar` file in PyTorch, no need to untar it.
